<?php

namespace Database\Seeders;

use App\Models\VehicleMake;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehicleMakesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $makes = [
            ['name' => 'abarth', 'vehicle_type' => 'car'],
            ['name' => 'acura', 'vehicle_type' => 'car'],
            ['name' => 'aiways', 'vehicle_type' => 'car'],
            ['name' => 'alfa romeo', 'vehicle_type' => 'car'],
            ['name' => 'alpina', 'vehicle_type' => 'car'],
            ['name' => 'alpine', 'vehicle_type' => 'car'],
            ['name' => 'aston martin', 'vehicle_type' => 'car'],
            ['name' => 'audi', 'vehicle_type' => 'car'],
            ['name' => 'baic', 'vehicle_type' => 'car'],
            ['name' => 'bentley', 'vehicle_type' => 'car'],
            ['name' => 'bmw', 'vehicle_type' => 'car'],
            ['name' => 'bordrin', 'vehicle_type' => 'car'],
            ['name' => 'borgward', 'vehicle_type' => 'car'],
            ['name' => 'bugatti', 'vehicle_type' => 'car'],
            ['name' => 'buick', 'vehicle_type' => 'car'],
            ['name' => 'byd', 'vehicle_type' => 'car'],
            ['name' => 'cadillac', 'vehicle_type' => 'car'],
            ['name' => 'caterham', 'vehicle_type' => 'car'],
            ['name' => 'chery', 'vehicle_type' => 'car'],
            ['name' => 'chevrolet', 'vehicle_type' => 'car'],
            ['name' => 'chrysler', 'vehicle_type' => 'car'],
            ['name' => 'citroën', 'vehicle_type' => 'car'],
            ['name' => 'daihatsu', 'vehicle_type' => 'car'],
            ['name' => 'denza', 'vehicle_type' => 'car'],
            ['name' => 'de tomaso', 'vehicle_type' => 'car'],
            ['name' => 'dodge', 'vehicle_type' => 'car'],
            ['name' => 'dongfeng', 'vehicle_type' => 'car'],
            ['name' => 'faw', 'vehicle_type' => 'car'],
            ['name' => 'ferrari', 'vehicle_type' => 'car'],
            ['name' => 'fiat', 'vehicle_type' => 'car'],
            ['name' => 'fisker', 'vehicle_type' => 'car'],
            ['name' => 'ford', 'vehicle_type' => 'car'],
            ['name' => 'gmc', 'vehicle_type' => 'car'],
            ['name' => 'geely', 'vehicle_type' => 'car'],
            ['name' => 'genesis', 'vehicle_type' => 'car'],
            ['name' => 'great wall motors (gwm)', 'vehicle_type' => 'car'],
            ['name' => 'haval', 'vehicle_type' => 'car'],
            ['name' => 'honda', 'vehicle_type' => 'car'],
            ['name' => 'hongqi', 'vehicle_type' => 'car'],
            ['name' => 'human horizons (hiphi)', 'vehicle_type' => 'car'],
            ['name' => 'hyundai', 'vehicle_type' => 'car'],
            ['name' => 'infiniti', 'vehicle_type' => 'car'],
            ['name' => 'italdesign', 'vehicle_type' => 'car'],
            ['name' => 'jac motors', 'vehicle_type' => 'car'],
            ['name' => 'jaguar', 'vehicle_type' => 'car'],
            ['name' => 'jeep', 'vehicle_type' => 'car'],
            ['name' => 'jetour', 'vehicle_type' => 'car'],
            ['name' => 'kia', 'vehicle_type' => 'car'],
            ['name' => 'koenigsegg', 'vehicle_type' => 'car'],
            ['name' => 'lamborghini', 'vehicle_type' => 'car'],
            ['name' => 'lancia', 'vehicle_type' => 'car'],
            ['name' => 'land rover', 'vehicle_type' => 'car'],
            ['name' => 'leapmotor', 'vehicle_type' => 'car'],
            ['name' => 'lexus', 'vehicle_type' => 'car'],
            ['name' => 'li auto', 'vehicle_type' => 'car'],
            ['name' => 'lincoln', 'vehicle_type' => 'car'],
            ['name' => 'lotus', 'vehicle_type' => 'car'],
            ['name' => 'lucid motors', 'vehicle_type' => 'car'],
            ['name' => 'mahindra', 'vehicle_type' => 'car'],
            ['name' => 'maserati', 'vehicle_type' => 'car'],
            ['name' => 'maybach', 'vehicle_type' => 'car'],
            ['name' => 'mazda', 'vehicle_type' => 'car'],
            ['name' => 'mclaren', 'vehicle_type' => 'car'],
            ['name' => 'mercedes-benz', 'vehicle_type' => 'car'],
            ['name' => 'mg', 'vehicle_type' => 'car'],
            ['name' => 'mini', 'vehicle_type' => 'car'],
            ['name' => 'mitsubishi', 'vehicle_type' => 'car'],
            ['name' => 'mitsuoka', 'vehicle_type' => 'car'],
            ['name' => 'morgan', 'vehicle_type' => 'car'],
            ['name' => 'nio', 'vehicle_type' => 'car'],
            ['name' => 'nissan', 'vehicle_type' => 'car'],
            ['name' => 'opel', 'vehicle_type' => 'car'],
            ['name' => 'ora', 'vehicle_type' => 'car'],
            ['name' => 'pagani', 'vehicle_type' => 'car'],
            ['name' => 'peugeot', 'vehicle_type' => 'car'],
            ['name' => 'porsche', 'vehicle_type' => 'car'],
            ['name' => 'ram', 'vehicle_type' => 'car'],
            ['name' => 'renault', 'vehicle_type' => 'car'],
            ['name' => 'rimac', 'vehicle_type' => 'car'],
            ['name' => 'rivian', 'vehicle_type' => 'car'],
            ['name' => 'rolls-royce', 'vehicle_type' => 'car'],
            ['name' => 'saab', 'vehicle_type' => 'car'],
            ['name' => 'seres', 'vehicle_type' => 'car'],
            ['name' => 'smart', 'vehicle_type' => 'car'],
            ['name' => 'subaru', 'vehicle_type' => 'car'],
            ['name' => 'suzuki', 'vehicle_type' => 'car'],
            ['name' => 'tata', 'vehicle_type' => 'car'],
            ['name' => 'tesla', 'vehicle_type' => 'car'],
            ['name' => 'toyota', 'vehicle_type' => 'car'],
            ['name' => 'tvr', 'vehicle_type' => 'car'],
            ['name' => 'venturi', 'vehicle_type' => 'car'],
            ['name' => 'volkswagen (vw)', 'vehicle_type' => 'car'],
            ['name' => 'volvo', 'vehicle_type' => 'car'],
            ['name' => 'voyah', 'vehicle_type' => 'car'],
            ['name' => 'weltmeister (wm motor)', 'vehicle_type' => 'car'],
            ['name' => 'wiesmann', 'vehicle_type' => 'car'],
            ['name' => 'xpeng', 'vehicle_type' => 'car'],

            //FOR BIKE
            ['name' => 'aprilia', 'vehicle_type' => 'bike'],
            ['name' => 'ather', 'vehicle_type' => 'bike'],
            ['name' => 'bajaj', 'vehicle_type' => 'bike'],
            ['name' => 'benelli', 'vehicle_type' => 'bike'],
            ['name' => 'bmw motorrad', 'vehicle_type' => 'bike'],
            ['name' => 'ducati', 'vehicle_type' => 'bike'],
            ['name' => 'hero', 'vehicle_type' => 'bike'],
            ['name' => 'hero electric', 'vehicle_type' => 'bike'],
            ['name' => 'harley-davidson', 'vehicle_type' => 'bike'],
            ['name' => 'honda', 'vehicle_type' => 'bike'],
            ['name' => 'husqvarna', 'vehicle_type' => 'bike'],
            ['name' => 'indian motorcycle', 'vehicle_type' => 'bike'],
            ['name' => 'jawa', 'vehicle_type' => 'bike'],
            ['name' => 'kawasaki', 'vehicle_type' => 'bike'],
            ['name' => 'ktm', 'vehicle_type' => 'bike'],
            ['name' => 'lambretta', 'vehicle_type' => 'bike'],
            ['name' => 'mahindra two wheelers', 'vehicle_type' => 'bike'],
            ['name' => 'motoguzzi', 'vehicle_type' => 'bike'],
            ['name' => 'ola electric', 'vehicle_type' => 'bike'],
            ['name' => 'okinawa', 'vehicle_type' => 'bike'],
            ['name' => 'piaggio', 'vehicle_type' => 'bike'],
            ['name' => 'revolt motors', 'vehicle_type' => 'bike'],
            ['name' => 'royal enfield', 'vehicle_type' => 'bike'],
            ['name' => 'suzuki', 'vehicle_type' => 'bike'],
            ['name' => 'tvs', 'vehicle_type' => 'bike'],
            ['name' => 'triumph', 'vehicle_type' => 'bike'],
            ['name' => 'vespa', 'vehicle_type' => 'bike'],
            ['name' => 'yamaha', 'vehicle_type' => 'bike'],
            ['name' => 'yezdi', 'vehicle_type' => 'bike'],
            ['name' => 'zero motorcycles', 'vehicle_type' => 'bike'],
        ];


        foreach ($makes as $make) {
            VehicleMake::create([
                'name' => ucwords($make['name']),
                'vehicle_type' => $make['vehicle_type']
            ]);
        }
    }
}
